package xaero.pac.common.server.player.config;

public enum PlayerConfigOptionCategory {
	GENERAL_CLAIMS,
	BLOCK_PROTECTION,
	BLOCK_TRIGGERS,
	ENTITY_PROTECTION,
	PLAYER_PROTECTION,
	MOVEMENT,
	PROTECTION_FROM_ITEMS,
	PICKUP_PROTECTION,
	SPAWN_PROTECTION,
	MIXED_PROTECTION,
	GENERAL_PARTY;

}
